from __future__ import annotations

from datetime import date

from pydantic import ValidationError
from sqlalchemy.orm import Session

from app.config import settings
from app.models import CoachingRecommendation
from app.prompts.coaching_prompt import (
    COACHING_PROMPT_VERSION,
    COACHING_SYSTEM_PROMPT,
    build_coaching_user_prompt,
)
from app.schemas.coaching import CoachingAdvice, CoachingRecommendationRead
from app.services.coaching_context_service import coaching_context_service
from app.services.llm_service import llm_service
from app.services.workload_adjustment_service import workload_adjustment_service


class InvalidCoachingResponseError(ValueError):
    """Raised when the LLM response does not match the coaching contract."""


class PendingSessionChangesError(RuntimeError):
    """Raised rather than rolling back unrelated caller changes."""


class CoachingService:
    """Build, generate, validate, and persist a daily recommendation."""

    async def generate_daily_recommendation(
        self,
        db: Session,
        user_id: int,
        target_date: date,
    ) -> CoachingRecommendationRead:
        # 第一次检查 Session 是否有未保存修改后面代码会执行：db.rollback() 如果 Session 中存在其他未提交修改，rollback() 会把那些修改一起撤销。所以这里提前报错，防止意外丢失数据
        self._ensure_no_pending_changes(db)

        context = coaching_context_service.build_daily_context(
            db=db,
            user_id=user_id,
            target_date=target_date,
        )
        adjustment = workload_adjustment_service.calculate(context)
        # Close the read transaction before calling the LLM, so that any changes made by the LLM are not rolled back if the caller has pending changes.
        self._close_read_transaction(db)

        llm_result = await llm_service.generate_json(
            system_prompt=COACHING_SYSTEM_PROMPT,
            user_prompt=build_coaching_user_prompt(
                context=context,
                adjustment=adjustment,
            ),
        )
        advice = self._validate_advice(llm_result)

        #create a SQLAlchemy CoachingRecommendation object and persist it to the database
        recommendation = CoachingRecommendation(
            user_id=user_id,
            recommendation_date=target_date,
            readiness_score=adjustment.readiness_score,
            workload_multiplier=adjustment.workload_multiplier,
            workload_level=adjustment.workload_level,
            adjustment_reasons_json=adjustment.reasons,
            summary=advice.summary,
            recommendations_json=advice.model_dump(mode="json"),
            model_name=settings.ollama_model,
            prompt_version=COACHING_PROMPT_VERSION,
        )

        # Start a new transaction to persist the recommendation, ensuring that any pending changes from the caller are not rolled back.
        with db.begin():
            # add the recommendation to the session, this common object turn to pending state, so we can use it to refresh the object and get the ID
            db.add(recommendation)
            # Send the current changes to the database immediately, but do not commit the transaction yet. This allows us to refresh the recommendation object and get its ID.
            db.flush()
            # Reread the record from the database and update the current Python object. This will retrieve the value automatically generated by the database.
            db.refresh(recommendation)
            # turn SQLAlchemy object to Pydantic model, this will also validate the data and raise an error if the data is invalid
            result = CoachingRecommendationRead.model_validate(recommendation)
        # SQLAlchemy automatically commits the transaction after the code block completes successfully.

        # Return the Pydantic model to the caller. 
        return result

    # Private methods: @staticmethod means this method do not need to visit selt、cls. It is simply placed inside the class to organize related logic.
    @staticmethod
    def _ensure_no_pending_changes(db: Session) -> None:
        if db.new or db.dirty or db.deleted:
            raise PendingSessionChangesError(
                "Cannot generate coaching advice with pending database changes"
            )

    # @classmethod indicates that the first parameter is the class itself.This approach offers greater flexibility if subclasses are created in the future
    @classmethod
    def _close_read_transaction(cls, db: Session) -> None:
        # 再次检查是否存在未保存修改：虽然方法开始时已经检查过一次，但在构建 context 和计算 adjustment 的过程中，理论上可能有其他代码改变了 Sessio
        cls._ensure_no_pending_changes(db)
        if db.in_transaction():
            db.rollback()

    @staticmethod
    def _validate_advice(llm_result: dict) -> CoachingAdvice:
        try:
            return CoachingAdvice.model_validate(llm_result)
        except ValidationError as exc:
            raise InvalidCoachingResponseError(
                "Ollama returned an invalid coaching recommendation"
            ) from exc
        '''
            from exc 表示保留原始异常作为原因，形成异常链：
                InvalidCoachingResponseError
                caused by
                ValidationError
            这样上层代码看到的是业务异常：InvalidCoachingResponseError
            但日志中仍然可以查看原始 Pydantic 验证错误
        '''

coaching_service = CoachingService()
